### PR TITLE
Remove lombok.config

### PR DESCRIPTION
**Pull request by DustinLuck**
I've noticed that when I build CAS (gradlew clean build), the lombok.config file shows up as a modified file in git. This appears to be because EOLs have been changed from LF to CRLF (which makes sense as I'm building on Windows).

Since the first line in the file says, "This file is generated…", I believe it should be added to the .gitignore list and removed from source control. I confirmed that I can delete the file from my project folder and it regenerates when doing a build.

### CODE REVIEW

**Comment by mmoayyed** [comment]
Thanks for the patch.

This the wrong target for the change.

1. If you are using/running 6.3, you should change the destination branch of your PR.

2. If you are using/running 6.4, you should instead update the initializr:
https://apereo.github.io/cas/development/installation/WAR-Overlay-Initializr.html

Also, this cannot be removed from source control or ignored; it's required to be there. You could either ignore it locally, or modify the build to not generate the file, but it cannot be globally ignored by the project. Lombok config is required for extension and custom development of the overlay.

**Comment by mmoayyed** [comment]
You might also be interested in:
https://apereo.github.io/cas/development/release_notes/RC2.html#cas-initializr

**Comment by mmoayyed** [comment]
Additional instructions on how to disable the lombok.config generation can be found here:
https://docs.freefair.io/gradle-plugins/current/reference/#_io_freefair_lombok

Seems to me like you should be able to modify your build not generate this file using:

```
generateLombokConfig.enabled = false
```

You could issue a PR to the 6.3 branch with this setting in the build, and if you do, please leave it commented out so the generation is on by default.

**Comment by mmoayyed** [comment]
The file is certainly source source; it does have an effect on how source code is generated, processed and managed, and if you ignore it by default, someone else will have to undo that ignore rule when they have extensions/changes, which is fairly common for almost all CAS deployments.

**Comment by DustinLuck** [comment]
I was not aware that others make changes to that file for their environments.  Now that I know, I understand why it should remain in source control.

Thank you.

**Pull request closed without merging**
