### PR TITLE
Use maven war overlay plugin via io.freefair.war-overlay plugin

### PR DESCRIPTION
**Pull request by hdeadman**
This is uses the maven overlay plugin which is better supported than the current overlay plugin. The main feature it has over the current plugin is that it supports excludes patterns .

### CODE REVIEW

**Comment by hdeadman** [comment]
I had to change the war task to "bootWar" and add the overlay config to that. The spring boot gradle plugin docs say that the way it reacts to the presence of the war plugin is to disable the war task (among other things). Not sure what made it work before with the other war overlay plugin. 

I had to put quotes around build in the "dependsOn 'build'" in a few places, not sure why but I think the unquoted build keyword stopped working as soon as I commented out the other war overlay plugin.

When the new war overlay was defined in it's own gradle file the plugin wasn't being found so I added it directly to build.gradle and that worked. I think it is less code to have the plugin added directly from build.gradle.

I left a commented out example module in the dependencies section otherwise there as an example. 

I haven't tested all the various tasks I was able to "run" cas and add a dependency to it. I also tested that the excludes feature works. There are times when I need to update a dependency to make a vulnerability scan happy and excludes is a quick fix while waiting for new CAS releases or builds.

**Comment by mmoayyed** [comment]
- Does the new plugin work if CAS is to execute as a native executable? 
- Does the jib plugin work with the new plugin?
- Are there any changes to the build commands one has to invoke to build the overlay?
- Likewise, does the Dockerfile need updating to includes changes to build commands?

**Comment by hdeadman** [comment]
> * Does the new plugin work if CAS is to execute as a native executable?
Does this mean java -jar build\libs\cas.war? That works.
> * Does the jib plugin work with the new plugin?
The following works:
gradlew jibDockerBuild
docker run --rm -it org.apereo.cas/cas:latest
> * Are there any changes to the build commands one has to invoke to build the overlay?
I don't think there is any change. 
> * Likewise, does the Dockerfile need updating to includes changes to build commands?
The Dockerfile isn't working for me but I will look into it some more and figure out what is wrong.

**Comment by mmoayyed** [comment]
> Does this mean java -jar build\libs\cas.war? That works.

What about:

```
chmod +x build\libs\cas.war
build\libs\cas.war
```

If the build is configured to prepare and build a standalone executable with https://github.com/apereo/cas-overlay-template/blob/master/gradle.properties#L8.

**Comment by hdeadman** [comment]
I got the Dockerfile working, had to make sure the gradlew file had line feed endings and that the etc\cas\saml folder existed, which I did on master. I also confirmed that the war is identical regardless of which overlay plugin is used to build it so it should work as a native executable. 

Before I found this war plugin I had started the process of publishing a fork of the current overlay plugin CAS uses. I may need to do some more work on that to get it working (and it also supports exclusions) but I feel like this plugin is better supported because it wraps the maven overlay functionality which is better supported.

**Comment by mmoayyed** [comment]
All sounds good. Thanks for validating the configuration with the new plugin. Should this still be in WIP mode?

**Comment by hdeadman** [comment]
No, not WIP anymore, I think it should be good to go.

**Pull request merged**
