### PR TITLE
allow snapshots to be downloaded for command/cli jar

### PR DESCRIPTION
**Pull request by hdeadman**
The command/cli download wasn't working for snapshots. Since snapshots have timestamps on the file you pretty much have to use maven to download them (rather than wget or powershell). 

There are older versions of maven-dependency-plugin where the "get" would write the file to the destination of your choice but there was a message about the destination option being deprecated. With the newer version I had to use get and copy to get the jar in the target directory. 

build.sh calls the command "cli" and build.cmd uses "command", not sure which you prefer. 

I didn't spend too much time trying to run the commands but the couple I tried didn't seem to work. Is that still being worked on?

### CODE REVIEW

**Comment by mmoayyed** [comment]
Appreciate the patch. It's probably not worth doing this, simply because once the release is done you would be able to use the official jar, but it obviously doesn't hurt to add.

`cli` should be the official command flag. 

Commands should all work:
https://apereo.github.io/2017/10/30/intro-cas-cli-shell/

I recommend you start with 5.2 SNAPSHOT.

**Comment by hdeadman** [comment]
I updated the script to use cli. I think the 5.2.0-rc4 shell jar was missing all of its lib dependencies so I think I had to use the snapshot. 

I guess the only thing I noticed not working (while playing around) was that generate-jwt didn't work with the defaults. In your blog you list "generate-jwt --sub Misagh" and the option is now "generate-jwt --subject Misagh" but when I do that I get a "java.security.InvalidKeyException: Illegal key size" exception. 

Thanks.

**Comment by mmoayyed** [comment]
You're perfectly right. I did update the blog post.

As for the exception, do you have the JCE installed?

**Comment by mmoayyed** [comment]
Tried again with JCE and that took care of it. Give it another shot and post back if you find issues please.

**Pull request merged**
